### ISSUE TITLE
Error on getSite().url

### ISSUE THREAD

**Issue by elpuas** [ndiego/mega-menu-block#1]
I know this is experimental but i found an issue testing on my local, when you save the Mega Menu Block, It works as expected on the front end, but when you go back to the editor it throws an error when you refresh the editor:
```
TypeError: Cannot read properties of undefined (reading 'url')
    at edit.js:63:69
    at data.min.js?ver=7c62e39de0308c73d50c:9:2045
    at __unstableMarkListeningStores (data.min.js?ver=7c62e39de0308c73d50c:2:22094)
    at Object.__unstableMarkListeningStores (data.min.js?ver=7c62e39de0308c73d50c:2:22352)
    at p (data.min.js?ver=7c62e39de0308c73d50c:9:2010)
    at data.min.js?ver=7c62e39de0308c73d50c:9:2612
    at Qe (data.min.js?ver=7c62e39de0308c73d50c:9:2824)
    at Ye (data.min.js?ver=7c62e39de0308c73d50c:9:3141)
    at Edit (edit.js:63:27)
...
```
It seems that by the time the js is loaded and the block is render on the editor `getSite().url` retruns undefined which breaks the block, a quick fix was to adding a optional chaining operator before accessing the property fix the issue. This is probably known by you since it’s experimental, but just in case someone else encounters this issue while using it, I wanted to share the solution.

```
const siteUrl = useSelect( ( select ) => select( 'core' ).getSite()?.url );
```

By the way, thank you for all you do!

**Comment by ndiego** [comment]
Thanks @elpuas, just fixed it! 💪
