### ISSUE TITLE
Site Editor paths changed in 6.7

### ISSUE THREAD

**Issue by bmx269** [ndiego/mega-menu-block#5]
After the 6.7 update, the Site editor paths have been updated. This line needs to be updated.

https://github.com/ndiego/mega-menu-block/blob/96c30e11eab0f4edd80f17ff76e79ed0f6386779/src/edit.js#L66

This line should be updated to 

```js
       '/wp-admin/site-editor.php?postType=wp_template_part&categoryId=menu'
```

**Comment by bmx269** [comment]
Pull request is here: https://github.com/ndiego/mega-menu-block/pull/6

**Comment by ndiego** [comment]
Thanks, just merged it!
